version: '3'
services:
  mongo:
    image: mongo
    container_name: jguwekamongo
    restart: always
    deploy:
        node: replicated
        replicas: 2
  jguweka:
    image: jguweka/jguweka:OAS3
    container_name: jguwekarest
    restart: always
    deploy:
        node: replicated
        replicas: 5
        resources:
            limits:
                memory: 500m
                cpus: '0.001'
    links:
      - "mongo:mongodb"
    ports:
      - "8081:8080"
    depends_on:
      - mongo
    labels:
      - "service-name:jguweka"
      - "service-type:app-srv"
      - "environment:test"
